/**
 * Airbnb API client. // --- BEGIN generated by sdk/codegen/facade — do not edit ---
 */

import type { BaseClient } from "../internal/client.js";

/** Client for all Airbnb API operations. (Generated from the OpenAPI spec.) */
export class AirbnbClient {
  private readonly client: BaseClient;

  constructor(client: BaseClient) {
    this.client = client;
  }

  /** Search experiences. Generated from the OpenAPI spec; returns the raw response object. */
  async searchExperiences(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/airbnb/experiences", { params });
  }

  /** Get experience detail. Generated from the OpenAPI spec; returns the raw response object. */
  async getExperienceDetail(
    experienceId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/airbnb/experiences/${experienceId}`, { params });
  }

  /** Get listing detail. Generated from the OpenAPI spec; returns the raw response object. */
  async getListingDetail(
    roomId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/airbnb/listings/${roomId}`, { params });
  }

  /** Get availability calendar. Generated from the OpenAPI spec; returns the raw response object. */
  async getAvailabilityCalendar(
    roomId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/airbnb/listings/${roomId}/calendar`, { params });
  }

  /** Get listing reviews. Generated from the OpenAPI spec; returns the raw response object. */
  async getListingReviews(
    roomId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/airbnb/listings/${roomId}/reviews`, { params });
  }

  /** Search stays. Generated from the OpenAPI spec; returns the raw response object. */
  async searchStays(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/airbnb/search", { params });
  }
}
