/**
 * App-Store API client. // --- BEGIN generated by sdk/codegen/facade — do not edit ---
 */

import type { BaseClient } from "../internal/client.js";

/** Client for all App-Store API operations. (Generated from the OpenAPI spec.) */
export class AppStoreClient {
  private readonly client: BaseClient;

  constructor(client: BaseClient) {
    this.client = client;
  }

  /** Get app detail. Generated from the OpenAPI spec; returns the raw response object. */
  async getAppDetail(
    appId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/app-store/apps/${appId}`, { params });
  }

  /** Get app reviews. Generated from the OpenAPI spec; returns the raw response object. */
  async getAppReviews(
    appId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/app-store/apps/${appId}/reviews`, { params });
  }

  /** Top charts. Generated from the OpenAPI spec; returns the raw response object. */
  async topCharts(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/app-store/charts", { params });
  }

  /** Get developer apps. Generated from the OpenAPI spec; returns the raw response object. */
  async getDeveloperApps(
    artistId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/app-store/developers/${artistId}`, { params });
  }

  /** List genres. Generated from the OpenAPI spec; returns the raw response object. */
  async listGenres(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/app-store/genres", { params });
  }

  /** List markets. Generated from the OpenAPI spec; returns the raw response object. */
  async listMarkets(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/app-store/markets", { params });
  }

  /** Search apps. Generated from the OpenAPI spec; returns the raw response object. */
  async searchApps(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/app-store/search", { params });
  }
}
