/**
 * Idealista API client. // --- BEGIN generated by sdk/codegen/facade — do not edit ---
 */

import type { BaseClient } from "../internal/client.js";

/** Client for all Idealista API operations. (Generated from the OpenAPI spec.) */
export class IdealistaClient {
  private readonly client: BaseClient;

  constructor(client: BaseClient) {
    this.client = client;
  }

  /** Agency by phone. Generated from the OpenAPI spec; returns the raw response object. */
  async agencyByPhone(
    phone: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/idealista/agency/by-phone/${phone}`, { params });
  }

  /** Agency profile + listings. Generated from the OpenAPI spec; returns the raw response object. */
  async agencyProfileListings(
    shortName: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/idealista/agency/${shortName}`, { params });
  }

  /** List markets. Generated from the OpenAPI spec; returns the raw response object. */
  async listMarkets(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/idealista/markets", { params });
  }

  /** Get property detail. Generated from the OpenAPI spec; returns the raw response object. */
  async getPropertyDetail(
    propertyCode: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/idealista/properties/${propertyCode}`, { params });
  }

  /** Get listing engagement stats. Generated from the OpenAPI spec; returns the raw response object. */
  async getListingEngagementStats(
    propertyCode: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/idealista/properties/${propertyCode}/stats`, { params });
  }

  /** Search listings. Generated from the OpenAPI spec; returns the raw response object. */
  async searchListings(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/idealista/search", { params });
  }

  /** Search all (beats result cap). Generated from the OpenAPI spec; returns the raw response object. */
  async searchAllBeatsResultCap(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/idealista/search/all", { params });
  }

  /** Resolve locations. Generated from the OpenAPI spec; returns the raw response object. */
  async resolveLocations(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/idealista/suggest", { params });
  }
}
