/**
 * Booking API client. // --- BEGIN generated by sdk/codegen/facade — do not edit ---
 */

import type { BaseClient } from "../internal/client.js";

/** Client for all Booking API operations. (Generated from the OpenAPI spec.) */
export class BookingClient {
  private readonly client: BaseClient;

  constructor(client: BaseClient) {
    this.client = client;
  }

  /** Search destinations. Generated from the OpenAPI spec; returns the raw response object. */
  async searchDestinations(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/booking/destinations", { params });
  }

  /** Get property detail. Generated from the OpenAPI spec; returns the raw response object. */
  async getPropertyDetail(
    countryCode: string,
    slug: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/booking/properties/${countryCode}/${slug}`, { params });
  }

  /** Get property reviews. Generated from the OpenAPI spec; returns the raw response object. */
  async getPropertyReviews(
    countryCode: string,
    slug: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/booking/properties/${countryCode}/${slug}/reviews`, { params });
  }

  /** Get room types and live rates. Generated from the OpenAPI spec; returns the raw response object. */
  async getRoomTypesAndLiveRates(
    countryCode: string,
    slug: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/booking/properties/${countryCode}/${slug}/rooms`, { params });
  }

  /** Search properties. Generated from the OpenAPI spec; returns the raw response object. */
  async searchProperties(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/booking/search", { params });
  }
}
