/**
 * Google-Play API client. // --- BEGIN generated by sdk/codegen/facade — do not edit ---
 */

import type { BaseClient } from "../internal/client.js";

/** Client for all Google-Play API operations. (Generated from the OpenAPI spec.) */
export class GooglePlayClient {
  private readonly client: BaseClient;

  constructor(client: BaseClient) {
    this.client = client;
  }

  /** Get app detail. Generated from the OpenAPI spec; returns the raw response object. */
  async getAppDetail(
    appId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/google-play/apps/${appId}`, { params });
  }

  /** Get app permissions. Generated from the OpenAPI spec; returns the raw response object. */
  async getAppPermissions(
    appId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/google-play/apps/${appId}/permissions`, { params });
  }

  /** Get app reviews. Generated from the OpenAPI spec; returns the raw response object. */
  async getAppReviews(
    appId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/google-play/apps/${appId}/reviews`, { params });
  }

  /** Get similar apps. Generated from the OpenAPI spec; returns the raw response object. */
  async getSimilarApps(
    appId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/google-play/apps/${appId}/similar`, { params });
  }

  /** List categories. Generated from the OpenAPI spec; returns the raw response object. */
  async listCategories(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/google-play/categories", { params });
  }

  /** Browse a category. Generated from the OpenAPI spec; returns the raw response object. */
  async browseACategory(
    categoryId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/google-play/categories/${categoryId}`, { params });
  }

  /** Top charts. Generated from the OpenAPI spec; returns the raw response object. */
  async topCharts(
    collection: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/google-play/collections/${collection}`, { params });
  }

  /** Get developer apps. Generated from the OpenAPI spec; returns the raw response object. */
  async getDeveloperApps(
    developer: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/google-play/developers/${developer}`, { params });
  }

  /** List markets. Generated from the OpenAPI spec; returns the raw response object. */
  async listMarkets(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/google-play/markets", { params });
  }

  /** Search apps. Generated from the OpenAPI spec; returns the raw response object. */
  async searchApps(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/google-play/search", { params });
  }
}
