/**
 * Facebook API client. // --- BEGIN generated by sdk/codegen/facade — do not edit ---
 */

import type { BaseClient } from "../internal/client.js";

/** Client for all Facebook API operations. (Generated from the OpenAPI spec.) */
export class FacebookClient {
  private readonly client: BaseClient;

  constructor(client: BaseClient) {
    this.client = client;
  }

  /** Search advertiser pages. Generated from the OpenAPI spec; returns the raw response object. */
  async searchAdvertiserPages(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/facebook/ads/pages/search", { params });
  }

  /** Get advertiser page info. Generated from the OpenAPI spec; returns the raw response object. */
  async getAdvertiserPageInfo(
    pageId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/facebook/ads/pages/${pageId}`, { params });
  }

  /** Search the Ad Library. Generated from the OpenAPI spec; returns the raw response object. */
  async searchTheAdLibrary(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/facebook/ads/search", { params });
  }

  /** Get an ad. Generated from the OpenAPI spec; returns the raw response object. */
  async getAnAd(
    adArchiveId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/facebook/ads/${adArchiveId}`, { params });
  }

  /** Get group detail. Generated from the OpenAPI spec; returns the raw response object. */
  async getGroupDetail(
    groupId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/facebook/groups/${groupId}`, { params });
  }

  /** Get group posts. Generated from the OpenAPI spec; returns the raw response object. */
  async getGroupPosts(
    groupId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/facebook/groups/${groupId}/posts`, { params });
  }

  /** List categories. Generated from the OpenAPI spec; returns the raw response object. */
  async listCategories(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/facebook/marketplace/categories", { params });
  }

  /** Browse a Marketplace category. Generated from the OpenAPI spec; returns the raw response object. */
  async browseAMarketplaceCategory(
    category: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/facebook/marketplace/category/${category}`, { params });
  }

  /** Get a Marketplace item. Generated from the OpenAPI spec; returns the raw response object. */
  async getAMarketplaceItem(
    itemId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/facebook/marketplace/item/${itemId}`, { params });
  }

  /** List locations. Generated from the OpenAPI spec; returns the raw response object. */
  async listLocations(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/facebook/marketplace/locations", { params });
  }

  /** Search Marketplace. Generated from the OpenAPI spec; returns the raw response object. */
  async searchMarketplace(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/facebook/marketplace/search", { params });
  }

  /** Get page detail. Generated from the OpenAPI spec; returns the raw response object. */
  async getPageDetail(
    identifier: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/facebook/pages/${identifier}`, { params });
  }

  /** Get page posts. Generated from the OpenAPI spec; returns the raw response object. */
  async getPagePosts(
    identifier: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/facebook/pages/${identifier}/posts`, { params });
  }

  /** Get post detail. Generated from the OpenAPI spec; returns the raw response object. */
  async getPostDetail(
    postId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/facebook/posts/${postId}`, { params });
  }

  /** Get post comments. Generated from the OpenAPI spec; returns the raw response object. */
  async getPostComments(
    postId: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/facebook/posts/${postId}/comments`, { params });
  }

  /** Get profile detail. Generated from the OpenAPI spec; returns the raw response object. */
  async getProfileDetail(
    identifier: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/facebook/profiles/${identifier}`, { params });
  }

  /** Get profile posts. Generated from the OpenAPI spec; returns the raw response object. */
  async getProfilePosts(
    identifier: string,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request(`/v1/facebook/profiles/${identifier}/posts`, { params });
  }

  /** Search everything. Generated from the OpenAPI spec; returns the raw response object. */
  async searchEverything(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/facebook/search", { params });
  }

  /** Search events. Generated from the OpenAPI spec; returns the raw response object. */
  async searchEvents(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/facebook/search/events", { params });
  }

  /** Search groups. Generated from the OpenAPI spec; returns the raw response object. */
  async searchGroups(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/facebook/search/groups", { params });
  }

  /** Search Pages. Generated from the OpenAPI spec; returns the raw response object. */
  async searchPages(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/facebook/search/pages", { params });
  }

  /** Search people. Generated from the OpenAPI spec; returns the raw response object. */
  async searchPeople(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/facebook/search/people", { params });
  }

  /** Search places. Generated from the OpenAPI spec; returns the raw response object. */
  async searchPlaces(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/facebook/search/places", { params });
  }

  /** Search posts. Generated from the OpenAPI spec; returns the raw response object. */
  async searchPosts(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/facebook/search/posts", { params });
  }
}
