/**
 * Account API client. // --- BEGIN generated by sdk/codegen/facade — do not edit ---
 */

import type { BaseClient } from "../internal/client.js";

/** Client for all Account API operations. (Generated from the OpenAPI spec.) */
export class AccountClient {
  private readonly client: BaseClient;

  constructor(client: BaseClient) {
    this.client = client;
  }

  /** Get account info. Generated from the OpenAPI spec; returns the raw response object. */
  async getAccountInfo(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/account/me", { params });
  }
}
