/**
 * Perplexity API client. // --- generated by sdk/codegen/facade — do not edit ---
 */

import type { BaseClient } from "../internal/client.js";

/** Client for all Perplexity API operations. (Generated from the OpenAPI spec.) */
export class PerplexityClient {
  private readonly client: BaseClient;

  constructor(client: BaseClient) {
    this.client = client;
  }

  /** Ask Perplexity a question. Generated from the OpenAPI spec; returns the raw response object. */
  async askPerplexityAQuestion(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/perplexity/ask", { params });
  }

  /** Ask Perplexity a question (POST). Generated from the OpenAPI spec; returns the raw response object. */
  async askPerplexityAQuestionPost(
    body?: unknown,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/perplexity/ask", { method: "POST", params, body });
  }

  /** Measure a brand's visibility in a Perplexity answer. Generated from the OpenAPI spec; returns the raw response object. */
  async measureABrandSVisibilityInAPerplexityAnswer(
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/perplexity/brand-visibility", { params });
  }

  /** Measure a brand's visibility in a Perplexity answer (POST). Generated from the OpenAPI spec; returns the raw response object. */
  async measureABrandSVisibilityInAPerplexityAnswerPost(
    body?: unknown,
    params: Record<string, string | number | boolean | undefined> = {}
  ): Promise<Record<string, unknown>> {
    return this.client.request("/v1/perplexity/brand-visibility", { method: "POST", params, body });
  }
}
